src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use IntlDateFormatter;

/**
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 */
class Employe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEmbauche;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getAge() 
    {
        $now = new \DateTime();
        $diff = $this->dateNaissance->diff($now);
        return $diff->format("%y ans");
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete() 
    {
        return $this->adresse." - ".$this->cp." ".$this->ville;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getDateEmbaucheFr()
    {
        $fmt = new IntlDateFormatter(
            "fr_FR",
            IntlDateFormatter::FULL,
            IntlDateFormatter::NONE,
            "Europe/Paris",
            IntlDateFormatter::GREGORIAN
        );

        return $fmt->format($this->dateEmbauche);
    }

    public function getAnciennete() 
    {
        $now = new \DateTime();
        $diff = $this->dateEmbauche->diff($now);
        $sp = $diff->y > 1 ? "ans" : "an";
        return $diff->format("%y $sp %m mois");
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function __toString() 
    {
        return $this->prenom." ".$this->nom;
    }

    public function getCollegues() {
        $collegues = [];
        foreach($this->getEntreprise()->getEmployes() as $employe) {
            if($this->getId() !== $employe->getId()) {
                $collegues[] = $employe;
            }
        }
        return $collegues;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Entity/Entreprise.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=EntrepriseRepository::class)
 */
class Entreprise
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $raisonSociale;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Employe::class, mappedBy="entreprise", orphanRemoval=true)
     * @OrderBy({"nom" = "ASC"})
     */
    private $employes;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateCreation;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): self
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete() 
    {
        return $this->adresse." - ".$this->cp." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->employes->contains($employe)) {
            $this->employes[] = $employe;
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->raisonSociale;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(?\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAnciennete() 
    {
        $now = new \DateTime();
        $diff = $this->dateCreation->diff($now);
        $sp = $diff->y > 1 ? "ans" : "an";
        return $diff->format("%y $sp %m mois");
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [
                    'class' => 'input-important',
                    // 'disabled' => true
                ]
            ])
            ->add('dateCreation', DateType::class, [
                'label' => 'Date de création',
                'widget' => 'single_text'
            ])
            ->add('siret', TextType::class, [
                'attr' => [
                    'placeholder' => 'Ex: 123456789'
                ]
            ])
            ->add('adresse', TextType::class)
            ->add('cp', TextType::class, [
                'label' => 'Code postal'
            ])
            ->add('ville', TextType::class)
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    /**
     * @Route("/entreprise", name="app_entreprise")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $entreprises = $doctrine->getRepository(Entreprise::class)->findBy([], ['raisonSociale' => 'ASC']);
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises,
        ]);
    }

    /**
     * @Route("/entreprise/add", name="add_entreprise")
     * @Route("/entreprise/update/{id}", name="update_entreprise")
     */
    public function add(ManagerRegistry $doctrine, Entreprise $entreprise = null, Request $request): Response
    {
        if(!$entreprise) {
            $entreprise = new Entreprise();
        }

        $entityManager = $doctrine->getManager();
        $form = $this->createForm(EntrepriseType::class, $entreprise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entreprise = $form->getData(); 
            $entityManager->persist($entreprise);
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        return $this->renderForm('entreprise/add.html.twig', [
            'form' => $form,
            'editMode' => $entreprise->getId()
        ]);
    }

    /**
     * @Route("/entreprise/delete/{id}", name="delete_entreprise")
     */
    public function delete(ManagerRegistry $doctrine, Entreprise $entreprise) {
        
        $entityManager = $doctrine->getManager();
        $entityManager->remove($entreprise);
        $entityManager->flush(); 
        return $this->redirectToRoute("app_entreprise");
    }

    /**
     * @Route("/entreprise/{id}", name="show_entreprise")
     */
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise,
        ]);
    }

}

templates/entreprise/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}

    {% if editMode %}
        <h1>Editer une entreprise</h1>
    {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}

    {# {{ form(form) }} #}

    {{ form_start(form) }}
        <div>
            {{ form_errors(form) }}
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.raisonSociale) }}
            </div>
            <div class="col">
                {{ form_row(form.siret) }}
            </div>
        </div>
        <div class="row">
            {{ form_row(form.dateCreation) }}
        </div>
        <div class="row">
            {{ form_row(form.adresse) }}
            <div class="col">
                {{ form_row(form.cp) }}
            </div>
            <div class="col">
                {{ form_row(form.ville) }}
            </div>
        </div>
    {{ form_end(form) }}

{% endblock %}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}

    <h1>Liste des entreprises <span class="bdg-primary">{{ entreprises | length }}</span></h1>

    <div>
        <h5>Rechercher par employé ou par entreprise</h5>
        {{ render(controller('App\\Controller\\SearchController::search')) }}
    </div>

    <p><a class="btn btn-success mt-3" href="{{ path('add_entreprise') }}"><i class="bi bi-plus-circle"></i> Ajouter une entreprise</a></p>

    <table class="table table-striped mt-5">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>ENTREPRISE</th>
                <th>EMPLOYES</th>
                <th>ACTIONS</th>
            </tr>
        </thead>
        <tbody>
        {% for entreprise in entreprises %}
            <tr class="align-middle">
                <td>{{ entreprise.id }}</td>
                <td><a href="{{ path('show_entreprise', {'id': entreprise.id} ) }}">{{ entreprise | upper }}</a></td>
                <td>{{ entreprise.employes | length }}</td>
                <td>
                    <a class="btn btn-action btn-danger" href="{{ path('delete_entreprise', {'id': entreprise.id }) }}"><i class="bi bi-trash"></i></a>
                    <a class="btn btn-action btn-warning" href="{{ path('update_entreprise', {'id': entreprise.id }) }}"><i class="bi bi-pencil-square"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}

    <h1><span><i class="bi bi-building"></i>&nbsp;</span>{{ entreprise }}</h1>

    <p><a title="Editer" class="btn btn-warning" href="{{ path('update_entreprise', {'id': entreprise.id }) }}"><i class="bi bi-pencil-square"></i></a></p>

    <p>
        <strong>Date de création :</strong> 
        {% if entreprise.dateCreation is not null %} 
            {{ entreprise.dateCreation | date('d-m-Y') ~ ' (' ~ entreprise.anciennete ~ ')'}} 
        {% else %}
            <span>N/A</span>    
        {% endif %} <br>
            
        <strong>Adresse :</strong> {{ entreprise.adresseComplete }} <br>
    </p>

    <h2 class="mt-5">Liste des employés <span class="bdg-primary">{{ entreprise.employes | length }}</span></h2>

    <table class="table table-striped">
        <thead class="bg-dark text-light">
            <tr>
                <th>Employé</th>
                <th>Date d'embauche</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employe in entreprise.employes %}
            <tr class="align-middle">
                <td><a href="{{ path('show_employe', {'id': employe.id }) }}">{{ employe }}</a></td>
                <td>{{ employe.dateEmbaucheFr }}</td>
                <td>
                    <a class="btn btn-action btn-danger" href="{{ path('delete_employe', {'id': employe.id }) }}"><i class="bi bi-trash"></i></a>
                    <a class="btn btn-action btn-warning" href="{{ path('update_employe', {'id': employe.id }) }}"><i class="bi bi-pencil-square"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}