src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use IntlDateFormatter;

/**
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 */
class Employe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEmbauche;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getAge() 
    {
        $now = new \DateTime();
        $diff = $this->dateNaissance->diff($now);
        return $diff->format("%y ans");
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete() 
    {
        return $this->adresse." - ".$this->cp." ".$this->ville;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getDateEmbaucheFr()
    {
        $fmt = new IntlDateFormatter(
            "fr_FR",
            IntlDateFormatter::FULL,
            IntlDateFormatter::NONE,
            "Europe/Paris",
            IntlDateFormatter::GREGORIAN
        );

        return $fmt->format($this->dateEmbauche);
    }

    public function getAnciennete() 
    {
        $now = new \DateTime();
        $diff = $this->dateEmbauche->diff($now);
        $sp = $diff->y > 1 ? "ans" : "an";
        return $diff->format("%y $sp %m mois");
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function __toString() 
    {
        return $this->prenom." ".$this->nom;
    }

    public function getCollegues() {
        $collegues = [];
        foreach($this->getEntreprise()->getEmployes() as $employe) {
            if($this->getId() !== $employe->getId()) {
                $collegues[] = $employe;
            }
        }
        return $collegues;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class, [
                'label' => 'Prénom'
            ])
            ->add('photo', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                    ])
                ],
            ])
            ->add('dateNaissance', DateType::class, [
                'label' => 'Date de naissance',
                'widget' => 'single_text'
            ])
            ->add('adresse', TextType::class)
            ->add('cp', TextType::class, [
                'label' => 'Code postal'
            ])
            ->add('ville', TextType::class)
            ->add('dateEmbauche', DateType::class, [
                'label' => 'Date d\'embauche',
                'widget' => 'single_text'
            ])
            ->add('entreprise', EntityType::class, [
                'label_attr' => [
                    'class' => 'fwb-red'
                ],
                'class' => Entreprise::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('e')
                        ->orderBy('e.raisonSociale', 'ASC');
                },
                'choice_label' => 'raisonSociale',
            ])
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class EmployeController extends AbstractController
{
    /**
     * @Route("/employe", name="app_employe")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $employes = $doctrine->getRepository(Employe::class)->findBy([], ['nom' => 'ASC']);
        return $this->render('employe/index.html.twig', [
            'employes' => $employes,
        ]);
    }

    /**
     * @Route("/employe/add", name="add_employe")
     * @Route("/employe/update/{id}", name="update_employe")
     */
    public function add(ManagerRegistry $doctrine, Employe $employe = null, SluggerInterface $slugger, Request $request): Response
    {
        if(!$employe) {
            $employe = new Employe();
        }

        $entityManager = $doctrine->getManager();
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $employe = $form->getData();
            $currentPhoto = $employe->getPhoto();
            $photo = $form->get('photo')->getData();

            if ($photo instanceof UploadedFile) {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);

                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();

                try {
                    $photo->move(
                        $this->getParameter('employes_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->redirectToRoute('app_employe');
                }

                $employe->setPhoto($newFilename);
            } else {
                if($currentPhoto == null) {
                    $employe->setPhoto('notavailable.jpeg');
                } else {
                    $employe->setPhoto($currentPhoto);
                }
            }

            $entityManager->persist($employe);
            $entityManager->flush();
            
            return $this->redirectToRoute('app_employe');
        }

        return $this->renderForm('employe/add.html.twig', [
            'form' => $form,
            'editMode' => $employe->getId()
        ]);
    }

    /**
     * @Route("/employe/delete/{id}", name="delete_employe")
     */
    public function delete(ManagerRegistry $doctrine, Employe $employe) {
        
        $entityManager = $doctrine->getManager();
        unlink($this->getParameter('employes_directory').$employe->getPhoto());
        $entityManager->remove($employe);
        $entityManager->flush(); 
        return $this->redirectToRoute("app_employe");
    }

    /**
     * @Route("/employe/{id}", name="show_employe")
     */
    public function show(Employe $employe = null): Response
    {
        if($employe == null) {
            return $this->redirectToRoute("app_employe");
        } else {
            return $this->render('employe/show.html.twig', [
                'employe' => $employe,
            ]);
        }
    }
}

templates/employe/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un employé{% endblock %}

{% block body %}

    {% if editMode %}
        <h1>Editer un employé</h1>
    {% else %}
        <h1>Ajouter un employé</h1>
    {% endif %}

    {{ form_start(form) }}
        <div>
            {{ form_errors(form) }}
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.nom) }}
            </div>
            <div class="col">
                {{ form_row(form.prenom) }}
            </div>
        </div>
        <div class="row">
            {{ form_row(form.photo) }}
        </div>
        <div class="row">
            {{ form_row(form.adresse) }}
            <div class="col">
                {{ form_row(form.cp) }}
            </div>
            <div class="col">
                {{ form_row(form.ville) }}
            </div>
        </div>
        <div class="row">
            {{ form_row(form.dateNaissance) }}
        </div>
        <div class="row">
            <div class="col">
                {{ form_row(form.dateEmbauche) }}
            </div>
            <div class="col">
                {{ form_row(form.entreprise) }}
            </div>
        </div>
    {{ form_end(form) }}

{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}

    <h1>Liste des employés <span class="bdg-primary">{{ employes | length }}</span></h1>

    <div>
      <h5>Rechercher par employé ou par entreprise</h5>
      {{ render(controller('App\\Controller\\SearchController::search')) }}
    </div>

    <p><a class="btn btn-success mt-3" href="{{ path('add_employe') }}"><i class="bi bi-plus-circle"></i> Ajouter un employé</a></p>

    <table class="table table-striped mt-5">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>EMPLOYE</th>
                <th>ENTREPRISE</th>
                <th>ACTIONS</th>
            </tr>
        </thead>
        <tbody>
        {% for employe in employes %}
            <tr class="align-middle">
                <td>{{ employe.id }}</td>
                <td><a href="{{ path('show_employe', {'id': employe.id} ) }}">{{ employe }}</a></td>
                <td><a href="{{ path('show_entreprise', {'id': employe.entreprise.id} ) }}">{{ employe.entreprise }}</a></td>
                <td>
                    {# <a data-bs-toggle="modal" data-bs-target="#modalSupp" class="btn btn-danger" href="{{ path('delete_employe', {'id': employe.id }) }}"><i class="bi bi-trash"></i></a> #}
                    <a class="btn btn-action btn-danger" href="{{ path('delete_employe', {'id': employe.id }) }}"><i class="bi bi-trash"></i></a>
                    <a class="btn btn-action btn-warning" href="{{ path('update_employe', {'id': employe.id }) }}"><i class="bi bi-pencil-square"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="modal fade" id="modalSupp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Suppression</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                Souhaitez-vous vraiment supprimer cet élément ?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
              <a class="btn btn-primary" href="{{ path('app_employe') }}">Confirmer</a>
            </div>
          </div>
        </div>
    </div>

{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une employé{% endblock %}

{% block body %}

    <h1><span><i class="bi bi-person"></i>&nbsp;</span>{{ employe }}</h1>

    <p><a title="Editer" class="btn btn-warning" href="{{ path('update_employe', {'id': employe.id }) }}"><i class="bi bi-pencil-square"></i></a></p>

    <p>
        <img class="photo_employe" src="{{ asset('uploads/photo_employes/' ~ employe.photo) }}" alt="">
    </p>

    <p>
        <strong>Entreprise :</strong> <a href="{{ path('show_entreprise', {'id':employe.entreprise.id}) }}">{{ employe.entreprise }}</a> <br>
        <strong>Date d'embauche :</strong> {{ employe.dateEmbauche | date('d-m-Y') ~ ' (' ~ employe.anciennete ~ ')' }} <br>
        <strong>Adresse :</strong> {{ employe.adresseComplete }} <br>
        <strong>Date de naissance :</strong> {{ employe.dateNaissance | date('d-m-Y') ~ ' (' ~ employe.age ~ ')'}} <br>
    </p>

    <h3 class="mt-5">Collègues <span class="bdg-primary">{{ employe.collegues | length }}</span></h3>
    
    <table class="table table-striped">
        <thead class="bg-dark text-light">
            <tr>
                <th>Employé</th>
            </tr>
        </thead>
        <tbody>
            {% if employe.collegues | length == 0 %}
               <tr><td>Aucun collègue référencé</td></tr> 
            {% else %}
                {% for emp in employe.collegues %}
                    <tr><td><a href="{{ path('show_employe', {'id':emp.id}) }}">{{ emp }}</a></td></tr>
                {% endfor %} 
            {% endif %}
        </tbody>
    </table>

{% endblock %}